name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Run a one-line script
      run: |
        $modules = Get-Module -Name Az.Accounts -ListAvailable
        Write-Host "======================"
        Write-Host $modules.path
        Write-Host "======================"
      shell:
        pwsh
